[build]
builder = "dockerfile"
dockerfilePath = "api/Dockerfile"
buildCommand = ""

[deploy]
startCommand = "node dist/server.js"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "api"
